# Designed to keep master branch as a perfect copy of LabKey fork
name: Sync Repos

on:
  workflow_dispatch:
  schedule:
    - cron:  "15 */3 * * *"
jobs:
  sync-release-branches:
    if: github.repository == 'BimberLabInternal/LabDevKitModules'
    runs-on: ubuntu-latest
    steps:
      - name: "Sync Release Branches"
        uses: bimberlabinternal/DevOps/githubActions/branch-create@master
        with:
          source_repo: "labkey/LabDevKitModules"
          source_branch_prefix: "release"
          destination_repo: "BimberLabInternal/LabDevKitModules"
          destination_branch_prefix: "discvr-"
          # NOTE: permissions are limited on the default secrets.GITHUB_TOKEN, including updating workflows, so use a personal access token
          github_token: ${{ secrets.PAT }}
  sync-master:
    if: github.repository == 'BimberLabInternal/LabDevKitModules'
    runs-on: ubuntu-latest
    steps:
      - name: "Sync Develop Branch"
        uses: bimberlabinternal/DevOps/githubActions/git-sync@master
        with:
          source_repo: "labkey/LabDevKitModules"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}
