# Designed to keep develop branch as a perfect copy of LabKey fork
on:
  schedule:
    - cron:  "*/15 * * * *"
jobs:
  sync-release-branches:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync Release Branches"
        uses: bimberlabinternal/DevOps/githubActions/branch-create@master
        with:
          source_repo: "labkey/LabDevKitModules"
          source_branch_prefix: "release"
          destination_repo: "BimberLabInternal/LabDevKitModules"
          destination_branch_prefix: "discvr-"
          github_token: ${{ secrets.GITHUB_TOKEN }}
